version: '3.4'

services:
   kpworker:
    #environment:
    #  - ConnectionString=Server=sql-server-db;Database=KPProducts;User=sa;Password=S3cur3P@ssW0rd!
    container_name: worker
    image: kpworker
    build:  
       context: .
       dockerfile: Worker.Dockerfile
    networks:
       - proxynet
    # depends_on:
    #    - db
   db:
    container_name: dbs
    image: kpdb
    build:
         context: .
         dockerfile: DB.Dockerfile
    environment:
        - ID=SA
        - SA_PASSWORD=S3cur3P@ssW0rd!
        - ACCEPT_EULA=Y
    networks:
       - proxynet
networks:
   proxynet:
    name: custom_network