version: '3.4'

services:
  kpworker:
    #environment:
    #  - ConnectionString=Server=sql-server-db;Database=KPProducts;User=sa;Password=S3cur3P@ssW0rd!;MultipleActiveResultSets=true;TrustServerCertificate=true
    container_name: worker-app
    image: ${DOCKER_REGISTRY-}kpworker
    build:  
      context: .
      dockerfile: KPWorker/Dockerfile
    depends_on:
      - db
  db:
    container_name: sql-server-db
    #image: "mcr.microsoft.com/mssql/server:2022-latest"
    build:
        dockerfile: KPWorker/DB/Dockerfile
    environment:
        - ID=SA
        - SA_PASSWORD=S3cur3P@ssW0rd!
        - ACCEPT_EULA=Y
    #restart: always
    ports:
     - "1433:1433"
