version: '3.4'

services:
  kpworker:
    image: ${DOCKER_REGISTRY-}kpworker
    build:
      context: .
      dockerfile: KPWorker/Dockerfile
    environment:
      - ConnectionString=Data Source=sql.data;Initial Catalog=KPProducts;User Id=sa;Password=S3cur3P@ssW0rd!;Pooling=False;Max Pool Size=200;MultipleActiveResultSets=True
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
     - "5433:1433"

    environment:
       SA_PASSWORD: "S3cur3P@ssW0rd!"
       ACCEPT_EULA: "Y"
